name: Rust

on:
  workflow_dispatch:  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Test All Rust Projects
        run: |
          for crate in $(find . -name Cargo.toml -exec dirname {} \;); do
            echo "Building $crate"
            cargo build --manifest-path "$crate/Cargo.toml" --verbose
            echo "Testing $crate"
            cargo test --manifest-path "$crate/Cargo.toml" --verbose
          done
